<a href="https://colab.research.google.com/github/gwarnertt/AI_Project_4/blob/master/feature_matrix_perceptron%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
feature_matrix= np.array([[-4.81601172e-01,  1.78219634e-01, -4.85607833e-01, -2.45714826e-01, 3.15102003e-01, -3.48503741e-01,  5.47084432e-03 ,-1.87296141e-01, 3.78785307e-01 , 1.46515841e-01],
                [-3.63061486e-01 ,-3.22479182e-01, -3.10852781e-01 , 4.19266650e-04,-4.26343343e-01 ,-6.78544931e-02, -3.68202611e-01 ,-1.59134843e-01,-4.72686307e-01 , 3.26099378e-01]])
print(feature_matrix.shape)
labels= [-1,  1 ]
T= 5
nsamples,columns = np.shape(feature_matrix)


def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):

    # Your code here
    print(np.multiply(feature_vector,current_theta.T))
    if (np.dot(feature_vector,current_theta)+current_theta_0)*label<=0:
        current_theta = current_theta+(label*feature_vector)
        current_theta_0= current_theta_0+label
    return current_theta,current_theta_0


def perceptron(feature_matrix, labels, T):
    def get_order(feature_matrix):
        return (list(range(nsamples)))

    (theta,theta_0)= (np.zeros(columns),0)
    n = get_order(feature_matrix.shape[0])
    print(n)
    for t in range(T):
        for i in n:
            print(feature_matrix[i])
            print(labels[i])
            print(theta)
            theta, theta_0 = perceptron_single_step_update(feature_matrix[i],labels[i],theta,theta_0)
        return (theta,theta_0)

perceptron(feature_matrix, labels, T)




(2, 10)
[0, 1]
[-0.48160117  0.17821963 -0.48560783 -0.24571483  0.315102   -0.34850374
  0.00547084 -0.18729614  0.37878531  0.14651584]
-1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[-0.  0. -0. -0.  0. -0.  0. -0.  0.  0.]
[-3.63061486e-01 -3.22479182e-01 -3.10852781e-01  4.19266650e-04
 -4.26343343e-01 -6.78544931e-02 -3.68202611e-01 -1.59134843e-01
 -4.72686307e-01  3.26099378e-01]
1
[ 0.48160117 -0.17821963  0.48560783  0.24571483 -0.315102    0.34850374
 -0.00547084  0.18729614 -0.37878531 -0.14651584]
[-1.74850837e-01  5.74721218e-02 -1.50952545e-01  1.03020032e-04
  1.34341641e-01 -2.36475447e-02  2.01437916e-03 -2.98053420e-02
  1.79046628e-01 -4.77787246e-02]


(array([ 0.11853969, -0.50069882,  0.17475505,  0.24613409, -0.74144535,
         0.28064925, -0.37367346,  0.0281613 , -0.85147161,  0.17958354]),
 0)